version: '3'

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8888:8080"
    volumes:
      - ../volumes/jenkins:/var/jenkins_home
    networks:
      - docker_network

  ubuntu_slave:
    depends_on:
        - jenkins
    build: 
      context: ../dockerfiles/slave
    command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8888/computer/dockerslave/jenkins-agent.jnlp -secret 7aab355c137cfeb1b469fc499ee26bdd95ca60621aecefacdc3203055a77613b -workDir "/home"
    container_name: ubuntucompose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_network
  
  selenium_hub: 
    image: selenium/hub:4.0.0-20211102
    container_name: selenium-hubcompose
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - docker_network

  selenium_firefox:
    image: selenium/node-firefox:4.0.0-20211102
    container_name: firefoxcompose
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hubcompose
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - docker_network

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    volumes:
      - ../volumes/artifactory:/var/opt/jfrog/artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    networks:
      - docker_network
    
networks:
  docker_network:
    driver: bridge
